#!/usr/bin/env bash

# A script to generate a bitbake include recipe via cargo-bitbake and compare it to one in meta-tulip
# Use the REL_DIR to find everything. Should be set to `export REL_DIR="$PWD"` prior to execution.
REL_DIR="${REL_DIR:?Relative directory (REL_DIR) must be set.}"

# Set the various variables
TULIP="$REL_DIR/${TULIP:?Tulip directory must be set.}"
META="$REL_DIR/${META:?Meta Tulip directory must be set.}"
CARGO_BITBAKE="${CARGO_BITBAKE:-$REL_DIR/cargo-bitbake}"

# If needed, the meta-tulip branch will be the same as the tulip branch to make tracking easier.
# An `-auto-ci` is appended to prevent name conflicts
BRANCH="${BRANCH}-auto-ci"

(
    cd $TULIP
    # Generate the new one.
    $CARGO_BITBAKE/precompiled/cargo-bitbake bitbake -t $CARGO_BITBAKE/templates/bitbake.inc.template

    cd $META
    # Switch to or create the new branch
    # This also will overwrite an existing branch
    git switch -C $BRANCH
    # Add the new file.
    cp -f $TULIP/*.inc $META/
    
    # Returns exit 1 if there is a difference
    # Returns exit 0 if there is no difference
    #git diff --quiet --exit-code
)
